[metadata]
version = "1.0"

[versions]
# Code quality
annotations = "26.0.1"
lombok = "1.18.36"

[libraries]
# Code quality
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }


[bundles]
utils = ["annotations", "lombok"]