[metadata]
version = "1.0"

[versions]
# Code quality
annotations = "26.0.1"
lombok = "1.18.36"

# Networking
grpc = "1.69.0"

[libraries]
# Code quality
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# Networking
grpc-netty =  { group = "io.grpc", name = "grpc-netty-shaded", version.ref = "grpc" }
grpc-protobuf =  { group = "io.grpc", name = "grpc-protobuf", version.ref = "grpc" }
grpc-stub =  { group = "io.grpc", name = "grpc-stub", version.ref = "grpc" }


[bundles]
utils = ["annotations", "lombok"]
grpc = ["grpc-netty", "grpc-protobuf", "grpc-stub"]